// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szjtbvsflldyvehuydxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6anRidnNmbGxkeXZlaHV5ZHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDM5MjgsImV4cCI6MjA1NzE3OTkyOH0.zdoVts6aEx7MSddNlpmQpzwSBGINMbNbP3f7FRH4UJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);