// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug logging (only in development)
if (typeof window !== 'undefined' && import.meta.env.DEV) {
  console.log('🔍 Supabase Config Check:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    urlPreview: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 30)}...` : 'missing',
    keyPreview: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'missing',
  });
}

// Check if we're using placeholder values (indicates missing env vars)
export const isSupabaseConfigured = !!(SUPABASE_URL && 
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL !== 'https://placeholder.supabase.co' && 
  SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key');

// Validate environment variables and create client
let supabaseClient: ReturnType<typeof createClient<Database>>;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  console.error(
    `❌ Missing required environment variables: ${missingVars.join(', ')}\n` +
    `Please create a .env file with:\n` +
    `VITE_SUPABASE_URL=your_supabase_url\n` +
    `VITE_SUPABASE_PUBLISHABLE_KEY=your_publishable_key`
  );
  
  // Create a dummy client to prevent crashes, but operations will fail
  // This allows the app to load and show error messages instead of crashing
  const dummyUrl = 'https://placeholder.supabase.co';
  const dummyKey = 'placeholder-key';
  
  supabaseClient = createClient<Database>(dummyUrl, dummyKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  });
  
  // Show user-friendly error in console
  if (typeof window !== 'undefined') {
    console.error('⚠️ Supabase configuration is missing. Please check your .env file.');
  }
} else {
  // Import the supabase client like this:
  // import { supabase } from "@/integrations/supabase/client";

  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  });

  // Log real-time connection status in development
  if (typeof window !== 'undefined' && import.meta.env.DEV) {
    // Monitor realtime connection through channel subscriptions
    // Connection status is tracked via individual channel subscriptions
    console.log('✅ Supabase Realtime: Client initialized with WebSocket support');
  }
}

export const supabase = supabaseClient;

/**
 * Helper function to check real-time connection status
 * Returns true if WebSocket connection is active
 */
export const getRealtimeConnectionStatus = (): boolean => {
  if (!supabaseClient) return false;
  const realtime = supabaseClient.realtime;
  if (!realtime) return false;
  
  // Check if there are any active channels
  const channels = realtime.channels;
  if (!channels || channels.length === 0) return false;
  
  // Check if at least one channel is subscribed
  return channels.some(channel => channel.state === 'joined');
};